In [32]:
import pandas as pd
import math

In [33]:
sample_text = ['holder ha it attack when the holder attempt to use a move all it other move are disabled until it leaf battle or loses this item the restriction end even if this item is swapped for another choice item via trick or switcheroo'
,'experience is split across two group pokemon who participated in battle and pokemon holding this item each pokemon earns experience a though it had battled alone divided by the number of pokemon in it group then divided by the number of group pokemon holding this item who also participated in battle effectively earn experience twice fainted pokemon never earn experience and empty group are ignored thus if a single pokemon is holding this item and the only pokemon who battled faint from explosion the holder will gain full experience'
,'damaged the holder for it max hp when the holder is struck by a contact move damage the attacker for it max hp if the attacker is not holding an item it will take this item'
,'trainer will skip encounter with wild pokemon of a lower level than the lead party pokemon this effect wear off after the trainer take step'
,'at the end of each turn if any of the holder stats have a negative stat modifier the holder consumes this item to remove the modifier from those stats']

In [34]:
from nltk.tokenize import word_tokenize
sentences = []
word_set = []

for sent in sample_text:
    words = [word.lower() for word in sent.split(sep=' ') if word.isalpha()]
    sentences.append(words)
    for word in words:
        if word not in word_set:
            word_set.append(word)
# Set of words
word_set = set(word_set)
# total documents in our corpus
total_docs = len(sample_text)
print('Total documents: ', total_docs)
print('Total words: ', len(word_set))

Total documents:  5
Total words:  109

In [81]:
tf_dict = {}
sent = sentences[3]
sent_len = len(sent)
for word in sent:
    tf_dict[word] = 0
for word in sent:
    tf_dict[word] += 1
for word in tf_dict.keys():
    tf_dict[word] = tf_dict[word] / sent_len

In [82]:
idf_dict = {}
for word in word_set:
    idf_dict[word] = 0
for word in word_set:
    for sentence in sentences:
        if word in sentence:
            idf_dict[word] += 1
for word in idf_dict.keys():
    idf_dict[word] = math.log(5 / idf_dict[word], 2)

In [83]:
tf_idf_dict = {}
for word in sent:
    tf_idf_dict[word] = tf_dict[word] * idf_dict[word]

In [84]:
df = pd.DataFrame(tf_idf_dict.values(), tf_idf_dict.keys(), columns=["TF-IDF"])
df = df.sort_values('TF-IDF', ascending=False)

In [85]:
df

             TF-IDF
trainer    0.185754
pokemon    0.105754
level      0.092877
after      0.092877
off        0.092877
wear       0.092877
effect     0.092877
party      0.092877
lead       0.092877
than       0.092877
lower      0.092877
wild       0.092877
with       0.092877
encounter  0.092877
skip       0.092877
step       0.092877
take       0.052877
will       0.029479
of         0.029479
the        0.000000
a          0.000000
this       0.000000

In [86]:
df

             TF-IDF
trainer    0.185754
pokemon    0.105754
level      0.092877
after      0.092877
off        0.092877
wear       0.092877
effect     0.092877
party      0.092877
lead       0.092877
than       0.092877
lower      0.092877
wild       0.092877
with       0.092877
encounter  0.092877
skip       0.092877
step       0.092877
take       0.052877
will       0.029479
of         0.029479
the        0.000000
a          0.000000
this       0.000000

In [87]:
df

             TF-IDF
trainer    0.185754
pokemon    0.105754
level      0.092877
after      0.092877
off        0.092877
wear       0.092877
effect     0.092877
party      0.092877
lead       0.092877
than       0.092877
lower      0.092877
wild       0.092877
with       0.092877
encounter  0.092877
skip       0.092877
step       0.092877
take       0.052877
will       0.029479
of         0.029479
the        0.000000
a          0.000000
this       0.000000

In [88]:
df

             TF-IDF
trainer    0.185754
pokemon    0.105754
level      0.092877
after      0.092877
off        0.092877
wear       0.092877
effect     0.092877
party      0.092877
lead       0.092877
than       0.092877
lower      0.092877
wild       0.092877
with       0.092877
encounter  0.092877
skip       0.092877
step       0.092877
take       0.052877
will       0.029479
of         0.029479
the        0.000000
a          0.000000
this       0.000000

In [89]:
df

             TF-IDF
trainer    0.185754
pokemon    0.105754
level      0.092877
after      0.092877
off        0.092877
wear       0.092877
effect     0.092877
party      0.092877
lead       0.092877
than       0.092877
lower      0.092877
wild       0.092877
with       0.092877
encounter  0.092877
skip       0.092877
step       0.092877
take       0.052877
will       0.029479
of         0.029479
the        0.000000
a          0.000000
this       0.000000